submissionOpen: true
submissionLabel: submission
submissionDir: submission/2019
images:
    small:
        width: 100
        height: 100
        sizeLimit: 1024
    big:
        width: 300
        height: 200
        sizeLimit: 1024
            
